#!/usr/bin/env node
/**
 * extract-acroform-fields.ts — Node CLI to extract AcroForm field metadata from a PDF
 * and emit YAML to stdout (or --out file).
 *
 * Dev-only tool. Not runtime code.
 *
 * Usage:
 *   tsx tools/extract-acroform-fields.ts --pdf path/to/form.pdf
 *   tsx tools/extract-acroform-fields.ts --pdf path/to/form.pdf --out skeleton.yml
 */

import { readFile, writeFile } from 'node:fs/promises';
import { resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { argv } from 'node:process';
import { PDFDocument } from 'pdf-lib';

// ─── Types ──────────────────────────────────────────────────────────────────

export interface ExtractedField {
  name: string;
  type: string;
  page: number;
  rect: [number, number, number, number];
}

// ─── Core extraction ────────────────────────────────────────────────────────

/**
 * Extract AcroForm widget metadata from raw PDF bytes.
 *
 * Strategy: iterate each field's widgets, match widget.P() to page.ref for
 * accurate page index. Falls back to page 0 with a comment if P() is missing.
 */
export async function extractAcroFormFields(
  pdfBytes: Uint8Array | Buffer | ArrayBuffer,
): Promise<ExtractedField[]> {
  const pdf = await PDFDocument.load(pdfBytes);
  const form = pdf.getForm();
  const fields = form.getFields();
  const pages = pdf.getPages();

  const results: ExtractedField[] = [];

  for (const field of fields) {
    const name = field.getName();
    const type = field.constructor.name;
    const widgets = field.acroField.getWidgets();

    for (const widget of widgets) {
      const rect = widget.getRectangle();
      const widgetPageRef = widget.P();

      // Match widget.P() to page.ref for accurate page index
      let pageIndex = -1;
      if (widgetPageRef) {
        for (let i = 0; i < pages.length; i++) {
          if (pages[i].ref === widgetPageRef) {
            pageIndex = i;
            break;
          }
        }
      }

      // Fallback: if P() is missing or no match, default to 0
      if (pageIndex === -1) pageIndex = 0;

      results.push({
        name,
        type,
        page: pageIndex,
        rect: [
          Math.round(rect.x * 100) / 100,
          Math.round(rect.y * 100) / 100,
          Math.round(rect.width * 100) / 100,
          Math.round(rect.height * 100) / 100,
        ],
      });
    }
  }

  return results;
}

// ─── YAML serialization ─────────────────────────────────────────────────────

export function fieldsToYaml(fields: ExtractedField[], pdfPath: string): string {
  const uniquePages = new Set(fields.map((f) => f.page));
  const lines: string[] = [];

  lines.push(`# Auto-extracted AcroForm fields from: ${basename(pdfPath)}`);
  lines.push('# Generated by app/tools/extract-acroform-fields.ts');
  lines.push('# Hand-edit to add: country, year, form, sourceUrl, sourceVersion, sourcePath, citation');
  lines.push('# DO NOT commit this raw output as a mapping — review every field, drop unused ones, add citations.');
  lines.push('');
  lines.push(`# Found ${fields.length} field widget(s) across ${uniquePages.size} page(s).`);
  lines.push('');
  lines.push('extracted_fields:');

  for (const f of fields) {
    lines.push(`  - name: ${JSON.stringify(f.name)}`);
    lines.push(`    type: ${f.type}`);
    lines.push(`    page: ${f.page}`);
    lines.push(`    rect: [${f.rect.join(', ')}]`);
    lines.push('');
  }

  return lines.join('\n');
}

// ─── CLI entrypoint ─────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const pdfArgIdx = args.indexOf('--pdf');

  if (pdfArgIdx === -1 || !args[pdfArgIdx + 1]) {
    console.error('Usage: tsx tools/extract-acroform-fields.ts --pdf <path> [--out <path>]');
    process.exit(1);
  }

  const pdfPath = resolve(args[pdfArgIdx + 1]);
  const outArgIdx = args.indexOf('--out');
  const outPath = outArgIdx !== -1 ? resolve(args[outArgIdx + 1]) : null;

  const pdfBytes = await readFile(pdfPath);
  const fields = await extractAcroFormFields(pdfBytes);
  const yaml = fieldsToYaml(fields, pdfPath);

  if (outPath) {
    await writeFile(outPath, yaml);
    console.error(`Wrote ${fields.length} fields to ${outPath}`);
  } else {
    process.stdout.write(yaml);
  }
}

// ─── Direct invocation guard ────────────────────────────────────────────────

const isMain =
  argv[1] !== undefined &&
  (fileURLToPath(import.meta.url) === argv[1] ||
    argv[1].replace(/\\/g, '/').endsWith('extract-acroform-fields.ts') ||
    argv[1].replace(/\\/g, '/').endsWith('extract-acroform-fields.js'));

if (isMain) {
  main().catch((err: Error) => {
    console.error('Error:', err.message);
    process.exit(1);
  });
}
